name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            See [CHANGELOG.md](https://github.com/Xartos/release-playground/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
      # - name: Get the version
      #   id: get_version
      #   run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0 HEAD)
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }} # ${{ steps.get_version.outputs.VERSION }}
      #     release_name: ${{ github.ref_name }} # ${{ steps.get_version.outputs.VERSION }}
      #     body: |
      #       See [CHANGELOG.md](https://github.com/Xartos/release-playground/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
